version: '3.9'

services:
  seed:
    build:
      context: ./seed
      args:
        buildno: 1
    networks:
      testing_net:
        ipv4_address: 172.28.1.1

  ordersvc:
    build:
      context: ./ordersvc
      args:
        buildno: 1
    environment:
      - DB_HOST=${DOCKER_GATEWAY_HOST:-host.docker.internal}
      - GDD_MEM_SEED=seed:56199
    expose:
      - "6062"
    ports:
      - "6062:6062"
    networks:
      testing_net:
        ipv4_address: 172.28.1.2
    depends_on:
      - seed
      - usersvc

  usersvc:
    build:
      context: ./usersvc
      args:
        buildno: 1
    environment:
      - DB_HOST=${DOCKER_GATEWAY_HOST:-host.docker.internal}
      - GDD_MEM_SEED=seed:56199
    expose:
      - "6061"
    ports:
      - "6061:6061"
    networks:
      testing_net:
        ipv4_address: 172.28.1.5
    depends_on:
      - seed

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16