version: '3.9'

services:
  seed:
    build:
      context: ./seed
      args:
        buildno: 1

  ordersvc:
    build:
      context: ./ordersvc
      args:
        buildno: 1
    environment:
      - DB_HOST=${DOCKER_GATEWAY_HOST:-host.docker.internal}
      - GDD_MEM_SEED=seed:56199
    expose:
      - "6062"
    ports:
      - "6062:6062"
    depends_on:
      - seed
      - usersvc

  usersvc:
    build:
      context: ./usersvc
      args:
        buildno: 1
    environment:
      - DB_HOST=${DOCKER_GATEWAY_HOST:-host.docker.internal}
      - GDD_MEM_SEED=seed:56199
    expose:
      - "6061"
    ports:
      - "6061:6061"
    depends_on:
      - seed

