/**
* Generated by go-doudou v2.0.0.
* Don't edit!
 */
package httpsrv

import (
	"net/http"

	"github.com/unionj-cloud/go-doudou/v2/framework"
	"github.com/unionj-cloud/go-doudou/v2/framework/rest"
)

type UsersvcHandler interface {
	PageUsers(w http.ResponseWriter, r *http.Request)
	GetUser(w http.ResponseWriter, r *http.Request)
	SignUp(w http.ResponseWriter, r *http.Request)
	UploadAvatar(w http.ResponseWriter, r *http.Request)
	UploadAvatar2(w http.ResponseWriter, r *http.Request)
	GetDownloadAvatar(w http.ResponseWriter, r *http.Request)
	GetUser2(w http.ResponseWriter, r *http.Request)
	PageUsers2(w http.ResponseWriter, r *http.Request)
	GetUser3(w http.ResponseWriter, r *http.Request)
	GetUser4(w http.ResponseWriter, r *http.Request)
	PageUsers3(w http.ResponseWriter, r *http.Request)
}

func Routes(handler UsersvcHandler) []rest.Route {
	return []rest.Route{
		{
			Name:        "PageUsers",
			Method:      "POST",
			Pattern:     "/page/users",
			HandlerFunc: handler.PageUsers,
		},
		{
			Name:        "GetUser",
			Method:      "GET",
			Pattern:     "/user",
			HandlerFunc: handler.GetUser,
		},
		{
			Name:        "SignUp",
			Method:      "POST",
			Pattern:     "/sign/up",
			HandlerFunc: handler.SignUp,
		},
		{
			Name:        "UploadAvatar",
			Method:      "POST",
			Pattern:     "/upload/avatar",
			HandlerFunc: handler.UploadAvatar,
		},
		{
			Name:        "UploadAvatar2",
			Method:      "POST",
			Pattern:     "/upload/avatar/2",
			HandlerFunc: handler.UploadAvatar2,
		},
		{
			Name:        "GetDownloadAvatar",
			Method:      "GET",
			Pattern:     "/download/avatar",
			HandlerFunc: handler.GetDownloadAvatar,
		},
		{
			Name:        "GetUser2",
			Method:      "GET",
			Pattern:     "/user/2",
			HandlerFunc: handler.GetUser2,
		},
		{
			Name:        "PageUsers2",
			Method:      "POST",
			Pattern:     "/page/users/2",
			HandlerFunc: handler.PageUsers2,
		},
		{
			Name:        "GetUser3",
			Method:      "GET",
			Pattern:     "/user/3",
			HandlerFunc: handler.GetUser3,
		},
		{
			Name:        "GetUser4",
			Method:      "GET",
			Pattern:     "/user/4",
			HandlerFunc: handler.GetUser4,
		},
		{
			Name:        "PageUsers3",
			Method:      "POST",
			Pattern:     "/page/users/3",
			HandlerFunc: handler.PageUsers3,
		},
	}
}

var RouteAnnotationStore = framework.AnnotationStore{}
