apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seed
spec:
  selector:
    matchLabels:
      app: seed
  serviceName: seed-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: seed
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: seed
          image: wubin1989/go-doudou-guide-seed:latest
#          ports:
#            - containerPort: 80
#              name: http
#              protocol: TCP
          volumeMounts:
            - name: storage
              mountPath: /var/tmp/cache
  volumeClaimTemplates:
    - metadata:
        name: storage
        annotations:
          volume.beta.kubernetes.io/storage-class: alicloud-disk-efficiency
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 20Gi
