apiVersion: v1
kind: Service
metadata:
  name: seed-svc-headless
spec:
  selector:
    app: seed
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 8080
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seed
spec:
  selector:
    matchLabels:
      app: seed
  serviceName: seed-svc-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: seed
    spec:
      terminationGracePeriodSeconds: 10
      nodeSelector:
        alias: node01
      containers:
        - name: seed
          image: wubin1989/go-doudou-guide-seed:latest
#          ports:
#            - containerPort: 80
#              name: http
#              protocol: TCP
          volumeMounts:
            - name: cache
              mountPath: /var/tmp/cache
      volumes:
        - name: cache
          hostPath:
            path: /var/tmp/cache
            type: DirectoryOrCreate
