{
 "title": "go-doudou-guide",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Circuitbreaker Command Execution Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(goresilience_command_execution_duration_seconds_count) by (id, success)"
    }
   ]
  },
  {
   "title": "Circuitbreaker State Changes Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(goresilience_circuitbreaker_state_changes_total) by (id, state) "
    }
   ]
  },
  {
   "title": "Response Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(response_status) by (job, status)"
    }
   ]
  },
  {
   "title": "Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(http_requests_total) by (job, instance)"
    }
   ]
  },
  {
   "title": "Average Response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg(http_response_time_seconds_sum/http_response_time_seconds_count) by (job)"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(http_requests_total[$__rate_interval])",
     "legendFormat": "{instance=\"{{instance}}\", job=\"{{job}}\"}"
    }
   ]
  }
 ]
}